### ISSUE TITLE
Error when installing from git

### ISSUE THREAD

**Issue by TenOs** [toumorokoshi/transmute-core#22] opened 2017-05-24 09:48 UTC
Hi I have the following line in my requirements.txt file:
```
git+https://github.com/toumorokoshi/transmute-core.git#egg=transmute-core
```

It seems that the installation with git does not set up the static folder (it's working fine when installing from pypi). It causes the following error:
```
Traceback (most recent call last):
  File "/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 396, in __init__
    directory = directory.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 1109, in resolve
    s = self._flavour.resolve(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/transmute_core/swagger/static'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/ex_py_commons/microservices/clients/http.py", line 39, in start
    '{}/swagger.json'.format(service_root_url))
  File "/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/aiohttp_transmute/swagger.py", line 47, in add_swagger_api_route
    app.router.add_static(STATIC_ROOT, static_root)
  File "/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 846, in add_static
    follow_symlinks=follow_symlinks)
  File "/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 401, in __init__
    "No directory exists at '{}'".format(directory)) from error
ValueError: No directory exists at '/Users/jbmartin/Developer/Expend/expend-expenses-api-service/.v_env/lib/python3.5/site-packages/transmute_core/swagger/static'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x107e8a940>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x107c3d9e8>
```

**Comment by toumorokoshi** [comment] 2017-05-24 17:02
@TenOs sorry about that! The git installation failed because the swagger files were not included with the package. They're downloaded during the build process, ensuring that it is published:

https://github.com/toumorokoshi/transmute-core/blob/master/ubuild.py#L65

I've committed the swagger files to the repo now. I can use that to install, and see statics, please re-open if it still reproduces for you.

**Closed by toumorokoshi** 2017-05-24 17:02 UTC
